### PR TITLE
add optional parameter for backoff schedule, fixes #86

### LINKED ISSUE #86: make message_retry schedule "configurable" in some way
https://github.com/mxenabled/action_subscriber/blob/master/lib/action_subscriber/message_retry.rb

Either  "global" config, or allow a single call to `redeliver_message_with_backoff` to take an optional argument that defines a custom retry schedule

some messages shouldn't jump from 12 seconds to 60 and then to 312 ... that's a long wait between retries

@mmmries

### PR DESCRIPTION
**Pull request by abrandoned**
include `retry` method (private) and make the backoff schedule an optional parameter in the retry method

@mmmries @film42

### CODE REVIEW

**Comment by mmmries** [comment]
I like the implementation of passing a retry schedule as a hash. Makes it pretty simple to change the number of retries and the delay at the same time.

Do you think the the DSL `retry` method should reschedule and `acknowledge` the current message? Or keep those separate? I guess it could be weird if you have `at_least_once!` mode turned on and it tried to double acknowledge?

**Comment by abrandoned** [comment]
@mmmries if we were to have the `retry` method `ack` then we would need to check which mode it is in and do the "most obvious" thing for that mode .... I didn't want the double ack scenario

your thoughts?

**Comment by mmmries** [comment]
Since all of our `ack`/`reject` calls go through the `ActionSubscriber::Middleware::Env` object, we could record if an ack/reject already happened and prevent the double-ack scenario. But that feels a bit strange to me. It could mask a bug where someone is acknowledging a message earlier than they think.

Detecting the current mode seems overly complicated so I'm :+1: for just leaving the ack/reject to the user. If you are running in `at_most_once!` mode your message has already been acked so calling `retry` works fine, and if you are running in `at_least_once!` mode your message will get acked at the end of the method which is fine as well.

The only problem would be `at_least_once!` mode where you raise an error after calling `retry` since that would duplicate your message.

Let's just make sure we document that calling `retry` does not do anything with the ack/reject

**Comment by mmmries** [comment]
Let's cut a pre-release from this branch and try it out in some part of the MX platform (sounds like grunt is where we want to use it first?)

Sorry if I'm being overly cautious, feel free to override if people feel differently. I just want to see it in use to verify that our assumptions work out the way we are thinking before I release it as a supported feature of the library.

**Comment by mmmries** [comment]
:+1: for `redeliver` to avoid confusion with `begin..rescue..retry`

**Comment by mmmries** [comment]
This has been tested multiple ways and run for multiple days in production with no issue so found. Going to merge and release as `4.3.0`

**Pull request merged**
